"""Pydantic data models for weekly digest, practice plans and GCS asynchronous ingestion (ADR-004)."""


from pydantic import BaseModel, Field

from src.models.memory import get_current_utc_iso


class PracticePlanDay(BaseModel):
    day: str = Field(..., description="Day of the week: 'Monday', 'Wednesday', 'Friday'")
    title: str = Field(..., description="Focus exercise title")
    description: str = Field(..., description="Specific practice instructions")
    target_metric: str = Field(..., description="Target geometric accuracy or line quality")


class WeeklyDigest(BaseModel):
    """Weekly digest generated by Cloud Scheduler aggregating progress and prescribing practice (ADR-004)."""

    digest_id: str
    student_id: str
    student_name: str
    week_id: str = Field(..., description="ISO week identifier, e.g. '2026-W34'")
    total_drawings: int
    weekly_avg_convergence_error_deg: float
    error_reduction_deg: float = Field(0.0, description="Positive value indicates reduction/improvement in error")
    recurring_issues: list[str]
    weekly_summary: str
    recommended_focus: str
    next_week_practice_plan: list[PracticePlanDay]
    created_at: str = Field(default_factory=get_current_utc_iso)


class WeeklyDigestRequest(BaseModel):
    student_id: str
    week_id: str | None = Field(None, description="Optional ISO week (defaults to current week)")


class GcsEventPayload(BaseModel):
    """Payload received from Eventarc on google.cloud.storage.object.v1.finalized event."""

    bucket: str = Field("atelier-inbox", description="GCS bucket name")
    name: str = Field(..., description="Object name in format '{student_id}/{filename}'")
    contentType: str | None = Field("image/png", description="MIME content type")
    image_base64: str | None = Field(None, description="Direct Base64 payload if forwarded via webhook/demo")


class GcsProcessingResponse(BaseModel):
    status: str = Field("processed", description="'processed' or 'failed'")
    exercise_id: str
    student_id: str
    student_name: str
    k_detected: int
    avg_convergence_error_deg: float
    critique_headline: str
    processed_at: str = Field(default_factory=get_current_utc_iso)
